# chr12:8,550,000-9,650,000 
# chr2:47500000-61150000
# --region chr2:55683901-61110893 
[x-axis]
# ################################################################################ NBC ######################################################################

# NBC
[NBC H3K4me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/NBC_III_H3K4me3_IHECRE00000354_1e738b62-fa24-41ee-be9b-480dc60cec32.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #FF0000
title = H3K4me3, H3K27ac, H3K4me1
transform = log1p
y_axis_values = original
min_value=0

[NBC H3K27ac]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/NBC_III_H3K27ac_IHECRE00000354_04d13593-4781-49ff-ae28-c33a62b39a3c.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #3366FF
transform = log1p
y_axis_values = original
min_value=0
overlay_previous = share-y
alpha = 0.5

[NBC H3K4me1]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/NBC_III_H3K4me1_IHECRE00000354_c6cc21cb-29f1-4521-bd26-ce2abe21aa06.fc.bigwig
# height of the track in cm (optional value)
color = #FF6633
height = 2
transform = log1p
y_axis_values = original
min_value=0
overlay_previous = share-y
alpha = 0.5

[NBC H3K36me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/NBC_III_H3K36me3_IHECRE00000354_0500ebd0-c650-482a-8d75-3cf5ca9c1882.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #990099
title = H3K36me3
transform = log1p
y_axis_values = original
min_value=0


[NBC H3K27me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/NBC_III_H3K27me3_IHECRE00000354_bacdb2f7-b47c-47dc-9b19-022a973c4a7a.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #663300
title = H3K27me3
transform = log1p
y_axis_values = original
min_value=0


[NBC H3K9me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/NBC_III_H3K9me3_IHECRE00000354_5883cd8d-0abd-4157-ab50-86a71ce76aaf.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #000066
title = H3K9me3
transform = log1p
y_axis_values = original
min_value=0

[NBC methylation]
file = /walter/projects/researchers/asalhab/EpiAtlas/analysis/segmentation/datafreez_2022/IHECRE00000354.2/IHECRE00000354.2.MSRvIHEC.20230209.GRCh38.CpG.meth.bw
# height of the track in cm (optional value)
height = 2
color = #00C81E
min_value = 0
max_value = 100
title = WGBS 


[NBC plus raw]
file = /walter/atlas/data/RNA-Seq/05-06-2022/ihec.rna-seq.ihec-grapenf-containerv1.1.0.IHECRE00000354.2.5cbd05e7-426f-493d-8f52-1621523dd006.Unique.plusRaw.bw
height = 2
title = RNA
color = #640A64
max_value = 0.817
grid=true
transform = log1p
y_axis_values = original



[compartments]
file = /walter/projects/students/nkster/projects/IHEC/hic/v2/bed-files/NBC_merged.bed
height = 1
title = Hi-C Comp.
fontsize = 10
file_type = bed
global_max_row = true
line_width = 0
color = bed_rgb
display = collapsed
labels = false


[NBC EpiSegmix meth ]
file =  /walter/projects/researchers/bins14/IHEC/Analysis/bed_files/NBC_I_EpiSegMixMeth_10N_relabelled.bed.gz
height = 1
title = EpiSegMixMeth 
fontsize = 10
file_type = bed
global_max_row = true
line_width = 0
labels = true
display = collapsed
color = bed_rgb
all_labels_inside = true
max_labels = 1000
labels = false

[spacer]
height = 0.15

[NBC arcs]
file = /walter/projects/researchers/bins14/IHEC/Analysis/significant_interactions/Heterochromatic_NBC_rep3_50000_long_range.circos.most.significant_interactions.arcs
title = Sig. interactions
line_width = 0.75
height = 1
color = darkred
orientation = inverted



[spacer]
height = 0.25

################################################################################## GCBC ######################################################################

[GCBC H3K4me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/GCBC_III_H3K4me3_IHECRE00000332_1a052aa3-c30b-4bd9-a36e-88509a9880d1.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #FF0000
title = H3K4me3, H3K27ac, H3K4me1
transform = log1p
y_axis_values = original
min_value=0



[GCBC H3K27ac]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/GCBC_III_H3K27ac_IHECRE00000332_3d98bc1f-c00a-45a1-9387-7764c6e8d313.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #3366FF
transform = log1p
y_axis_values = original
min_value=0
overlay_previous = share-y
alpha = 0.5

[GCBC H3K4me1]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/GCBC_III_H3K4me1_IHECRE00000332_5497448a-601c-483d-a9cd-9eaf651148a5.fc.bigwig
# height of the track in cm (optional value)
color = #FF6633
height = 2
transform = log1p
y_axis_values = original
min_value=0
overlay_previous = share-y
alpha = 0.5


[GCBC H3K36me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/GCBC_III_H3K36me3_IHECRE00000332_c9c514ac-1a99-4191-b0b0-7e14f38ebc7a.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #990099
title = H3K36me3
transform = log1p
y_axis_values = original
min_value=0

[GCBC H3K27me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/GCBC_III_H3K27me3_IHECRE00000332_10f5266d-441b-4d93-a883-d970677b92f6.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #663300
title = H3K27me3
transform = log1p
y_axis_values = original
min_value=0


[GCBC H3K9me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/GCBC_III_H3K9me3_IHECRE00000332_2d8d5533-830a-43b4-b551-587064ddf941.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #000066
title = H3K9me3
transform = log1p
y_axis_values = original
min_value=0


[GCBC methylation]
file = /walter/projects/researchers/asalhab/EpiAtlas/analysis/segmentation/datafreez_2022/IHECRE00000332.2/IHECRE00000332.2.MSRvIHEC.20230209.GRCh38.CpG.meth.bw
# height of the track in cm (optional value)
height = 2
color = #00C81E
min_value = 0
max_value = 100
title = WGBS


[GCBC plus raw]
file = /walter/atlas/data/RNA-Seq/05-06-2022/ihec.rna-seq.ihec-grapenf-containerv1.1.0.IHECRE00000332.2.0dd3b40f-bb15-4240-9bb5-71a0385bd0a2.Unique.plusRaw.bw
height = 2
title = RNA
color = #640A64
max_value = 0.817
grid=true
transform = log1p
y_axis_values = original

[compartments]
file = /walter/projects/students/nkster/projects/IHEC/hic/v2/bed-files/GCBC_merged.bed
height =  1
title =  Hi-C Comp. 
fontsize = 10
file_type = bed
global_max_row = true
line_width = 0
color = bed_rgb
display = collapsed
labels = false

[spacer]
height = 0.15

[GCBC EpiSegmix meth ]
file = /walter/projects/researchers/bins14/IHEC/Analysis/bed_files/GCBC_I_EpiSegMixMeth_10N_relabelled.bed.gz
height =  1
title = EpiSegMixMeth
fontsize = 10
file_type = bed
global_max_row = true
line_width = 0
labels = true
display = collapsed
color = bed_rgb
all_labels_inside = true
max_labels = 1000
labels = false


[spacer]
height = 0.15

[GCBC arcs]
file = /walter/projects/researchers/bins14/IHEC/Analysis/significant_interactions/Heterochromatic_GCBC_rep2_50000_long_range.circos.most.significant_interactions.arcs
title = Sig. interactions
#line_width = 0.8
height = 1
color = darkred
orientation = inverted

[spacer]
height = 0.20

################################################################################## MBC ######################################################################

# MBC
[MBC H3K4me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/MBC_I_H3K4me3_IHECRE00000335_df643b1b-9be3-4dd8-8c11-593655fbc96d.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #FF0000
title = H3K4me3, H3K27ac, H3K4me1
transform = log1p
y_axis_values = original
min_value=0

[MBC H3K27ac]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/MBC_I_H3K27ac_IHECRE00000335_a05422f9-2489-4507-8cda-057f9cf37c4f.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #3366FF
transform = log1p
y_axis_values = original
min_value=0
overlay_previous = share-y
alpha = 0.5

[MBC H3K4me1]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/MBC_I_H3K4me1_IHECRE00000335_cc603fdd-0221-4d9e-8597-71437d48b94f.fc.bigwig
# height of the track in cm (optional value)
color = #FF6633
height = 2
transform = log1p
y_axis_values = original
min_value=0
overlay_previous = share-y
alpha = 0.5

[MBC H3K36me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/MBC_I_H3K36me3_IHECRE00000335_2bc104d8-deb7-4fd8-ad67-65852c2b7651.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #990099
title = H3K36me3
transform = log1p
y_axis_values = original
min_value=0

[MBC H3K27me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/MBC_I_H3K27me3_IHECRE00000335_8483e047-3aa4-4475-9bf3-0f99733a4494.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #663300
title = H3K27me3
transform = log1p
y_axis_values = original
min_value=0

[MBC H3K9me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/MBC_I_H3K9me3_IHECRE00000335_095e5d9d-dd86-45e1-ab00-f7d920b15318.fc.bigwig
# height of the track in cm (optional value)
height = 1.75
color = #000066
title = H3K9me3
transform = log1p
y_axis_values = original
min_value=0

[MBC methylation]
file = /walter/projects/researchers/asalhab/EpiAtlas/analysis/segmentation/datafreez_2022/IHECRE00000335.2/IHECRE00000335.2.MSRvIHEC.20230209.GRCh38.CpG.meth.bw
# height of the track in cm (optional value)
height = 2
color = #00C81E
min_value = 0
max_value = 100
title = methylation

[MBC plus raw]
file = /walter/atlas/data/RNA-Seq/05-06-2022/ihec.rna-seq.ihec-grapenf-containerv1.1.0.IHECRE00000335.2.4534bbac-291c-4712-94a2-d18bb1f4978e.Unique.plusRaw.bw
height = 2
title = RNA
color = #640A64
max_value = 0.817
grid=true
transform = log1p
y_axis_values = original



[compartments]
file = /walter/projects/students/nkster/projects/IHEC/hic/v2/bed-files/MBC_merged.bed
height =  1
title = Hi-C Comp 
fontsize = 10
file_type = bed
global_max_row = true
line_width = 0
color = bed_rgb
display = collapsed
labels = false


[MBC EpiSegmix meth ]
file = /walter/projects/researchers/bins14/IHEC/Analysis/bed_files/MBC_II_EpiSegMixMeth_10N_relabelled.bed.gz
height =  1
title = EpiSegMixMeth
fontsize = 10
file_type = bed
global_max_row = true
line_width = 0
labels = true
display = collapsed
color = bed_rgb
all_labels_inside = true
max_labels = 1000
labels = false


[spacer]
height = 0.15
[MBC arcs]
file=/walter/projects/researchers/bins14/IHEC/Analysis/significant_interactions/Heterochromatic_MBC_rep1_50000_long_range.circos.most.significant_interactions.arcs
title = Sig. interactions
#line_width = 0.8
height = 2
color = darkred
min_value=8.0
orientation = inverted
file_type = links

[spacer]
height = 0.20


############################################################################################  PC ########################################################


[PC H3K4me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/PC_I_H3K4me3_IHECRE00000341_a7828873-27cd-49a4-bfd1-e91b3c208957.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #FF0000
transform = log1p
y_axis_values = original
title = H3K4me3, H3K27ac, H3K4me1
file_type = bigwig
min_value=0

[PC H3K27ac]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/PC_I_H3K27ac_IHECRE00000341_ae820aec-dd3a-42d0-a6fa-3860a5d53528.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #3366FF
transform = log1p
y_axis_values = original
file_type = bigwig
min_value=0
overlay_previous = share-y
alpha = 0.5

[PC H3K4me1]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/PC_I_H3K4me1_IHECRE00000341_b4ef1ce8-bd05-4993-ba65-94b4c3f02ba3.fc.bigwig
# height of the track in cm (optional value)
color = #FF6633
height = 2
transform = log1p
y_axis_values = original
file_type = bigwig
min_value=0
overlay_previous = share-y
alpha = 0.5

[PC H3K36me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/PC_I_H3K36me3_IHECRE00000341_4902afa5-c7f4-4ab6-9245-173867cb1883.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #990099
title = H3K36me3
transform = log1p
y_axis_values = original
file_type = bigwig
min_value=0

[PC H3K27me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/PC_I_H3K27me3_IHECRE00000341_1336f5ff-9ca0-4ebb-bcdd-719a4429b6e5.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #663300
title = H3K27me3
transform = log1p
file_type = bigwig
y_axis_values = original
min_value=0

[PC H3K9me3]
file = /walter/projects/researchers/bins14/IHEC/counts/B-cell/PC_I_H3K9me3_IHECRE00000341_60427f84-8516-4b50-8b0c-92e59f98bd58.fc.bigwig
# height of the track in cm (optional value)
height = 2
color = #000066
title = H3K9me3
transform = log1p
y_axis_values = original
file_type = bigwig
min_value=0

[PC methylation]
file = /walter/projects/researchers/asalhab/EpiAtlas/analysis/segmentation/datafreez_2022/IHECRE00000341.2/IHECRE00000341.2.MSRvIHEC.20230209.GRCh38.CpG.meth.bw
# height of the track in cm (optional value)
height = 2
color = #00C81E
min_value = 0
max_value = 100
title = WGBS

[PC plus raw]
file = /walter/atlas/data/RNA-Seq/05-06-2022/ihec.rna-seq.ihec-grapenf-containerv1.1.0.IHECRE00000341.2.8084c9f4-b0d4-4a65-a7d3-f99917853ec4.Unique.plusRaw.bw
height = 2
title = RNA
color = #640A64
max_value = 0.817
grid=true
transform = log1p
y_axis_values = original

[compartments]
file = /walter/projects/students/nkster/projects/IHEC/hic/v2/bed-files/PC_merged.bed
height =  1
title = Hi-C Comp.  
fontsize = 10
file_type = bed
global_max_row = true
line_width = 0
color = bed_rgb
display = collapsed
labels = false


[PC EpiSegmix meth]
file = /walter/projects/researchers/bins14/IHEC/Analysis/bed_files/PC_I_EpiSegMixMeth_10N_relabelled.bed.gz
height = 1
title = EpiSegMixMeth 
fontsize = 10
file_type = bed
global_max_row = true
line_width = 0
labels = true
display = collapsed
color = bed_rgb
all_labels_inside = true
max_labels = 1000
labels = false

[spacer]
height = 0.15

[PC arcs]
file = /walter/projects/researchers/bins14/IHEC/Analysis/significant_interactions/Heterochromatic_PC_rep1_50000_long_range.circos.most.significant_interactions.arcs
title =Sig. interactions
line_width = 0.75
height = 1
color = darkred
orientation = inverted

[spacer]
height = 0.15

[UCSC genes]
file = /walter/projects/researchers/bins14/references/genes/genes.gtf
height = 2
fontsize = 20
color = #6ad0ff
file_type = gtf
gene_rows = 3
labels = true
max_labels = 100
all_labels_inside = true
prefered_name = gene_name
merge_transcripts = true
merge_overlapping_exons = true
