[x-axis]
[hic matrix]
file = /walter/projects/students/nkster/projects/IHEC/hic/v2/GCBC/merged/GCBC_NBC_merged_50000_compared.cool
title = log2(GCBC/NBC)
file_type = hic_matrix
max_value: 2.5
min_value: -2.5
depth = 5500000
colormap= ['white',(0.25,0.50,0.58)]
colormap = ['blue','white','red']

[tads]
file = /walter/projects/students/nkster/projects/IHEC/hic/v2/GCBC/merged/GCBC_TADS_None_domains.bed
display = triangles
border_color = black
color = none
overlay_previous = share-y
line_width = 2

[spacer]
height = 0.15

[GCBC ChromHMM meth ]
file = /walter/projects/researchers/bins14/IHEC/Analysis/relabelled_bed_files/random_forest_classifier/ChromHMM/IHECRE00000332.2_ChromHMM_10N_relabelled.bed
height =  1
title = ChromHMM
fontsize = 10
file_type = bed
global_max_row = true
line_width = 0
labels = true
display = collapsed
color = bed_rgb
all_labels_inside = true
max_labels = 1000
labels = false




[spacer]
height = 0.15

[GCBC EpiSegmix ]
file = /walter/projects/researchers/bins14/IHEC/Analysis/relabelled_bed_files/random_forest_classifier/EpiSegMix/IHECRE00000332.2_EpiSegMix_10N_relabelled.bed
height =  1
title = EpiSegMix
fontsize = 10
file_type = bed
global_max_row = true
line_width = 0
labels = true
display = collapsed
color = bed_rgb
all_labels_inside = true
max_labels = 1000
labels = false


[spacer]
height = 0.15

[GCBC EpiSegmix meth ]
file = /walter/projects/researchers/bins14/IHEC/Analysis/bed_files/GCBC_I_EpiSegMixMeth_10N_relabelled.bed.gz
height =  1
title = EpiSegMixMeth
fontsize = 10
file_type = bed
global_max_row = true
line_width = 0
labels = true
display = collapsed
color = bed_rgb
all_labels_inside = true
max_labels = 1000
labels = false


[spacer]
height = 0.15

[GCBC arcs]
file = /walter/projects/researchers/bins14/IHEC/Analysis/significant_interactions/Heterochromatic_GCBC_rep2_50000_long_range.circos.most.significant_interactions.arcs
title = Sig. interactions
#line_width = 0.8
height = 1
color = darkred
orientation = inverted

[spacer]
height = 0.15

[UCSC genes]
file = /walter/projects/researchers/bins14/references/genes/genes.gtf
height = 2
fontsize = 20
color = #6ad0ff
file_type = gtf
gene_rows = 3
labels = true
max_labels = 100
all_labels_inside = true
prefered_name = gene_name
merge_transcripts = true
merge_overlapping_exons = true
